# Configure Default Memory, CPU Requests and Limits for a Namespace
# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

apiVersion: v1
kind: LimitRange
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}-limit-range
    kubernetes.io/created-by: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.namespace }}-limit-range
  namespace: {{ .Values.namespace }}
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: {{ .Values.defaultContainerLimits.defaultRequest.cpu | default "1m" }}
      memory: {{ .Values.defaultContainerLimits.defaultRequest.memory | default "4Mi" }}
    default:
      cpu: {{ .Values.defaultContainerLimits.default.cpu | default "10m" }}
      memory: {{ .Values.defaultContainerLimits.default.memory | default "10Mi" }}
    min:
      cpu: 0m
      memory: 0Mi
    max:
      # Memory cannot exceed the limits set in the namespace quotas, a pod cannot exceed the budget allocated by the namespace
      memory: {{ min .Values.defaultContainerLimits.max.memory .Values.namespaceQuotas.limits.memory | default "1Gi" }}
  - type: PersistentVolumeClaim
    max:
      storage: {{ .Values.namespaceQuotas.storage.max | default "1Gi" }}
    min:
      storage: {{ .Values.namespaceQuotas.storage.min | default "0Gi" }}
