apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    kubernetes.io/created-by: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ .Values.namespace }}