# Configure Memory and CPU Quotas for a Namespace
# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.rootTenantNamespace }}-resource-quota
    kubernetes.io/created-by: {{ .Chart.Name }}
  name: {{ .Values.rootTenantNamespace }}-resource-quota
  namespace: {{ .Values.rootTenantNamespace }}
spec:
  hard:
    requests.cpu: {{ .Values.tenantNamespaceResourceLimits.namespaceQuotas.requests.cpu }}
    requests.memory: {{ .Values.tenantNamespaceResourceLimits.namespaceQuotas.requests.memory }}
    # This is not a good pattern to enforce a hard limit on. Pods can always take advantage then of the extra CPU if available.
    # limits.cpu: "2"
    limits.memory: {{ .Values.tenantNamespaceResourceLimits.namespaceQuotas.limits.memory }}