apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-namespace-governor
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/debanjanbasu/k8s-namespace-governor.git
      revision: HEAD
      files:
      - path: "projects/**/values.yaml"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-k8s-governor-config'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        chart: ns-governor
        repoURL: https://debanjanbasu.github.io/k8s-namespace-governor
        targetRevision: 1.1.1
        # helm:
        #   valueFiles:
        #   - '{{filepath}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
