apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-namespace-governor
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/debanjanbasu/k8s-namespace-governor.git
      revision: HEAD
      files:
      - path: "projects/**/values.yaml"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-k8s-governor-config'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        # chart: ns-governor
        repoURL: https://github.com/debanjanbasu/k8s-namespace-governor.git
        path: ns-governor
        targetRevision: HEAD
        helm:
          valueFiles:
          # Move one level up to the parent directory
          - '../{{.path.path}}/{{.path.filenameNormalized}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
