apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-governor
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/debanjanbasu/k8s-namespace-governor.git
        revision: HEAD
        files:
          - path: "projects/**/*.yaml"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-{{ index (splitList "." .path.filenameNormalized) 0 }}-governor-config'
    spec:
      project: ns-governor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        # chart: ns-governor
        repoURL: https://github.com/debanjanbasu/k8s-namespace-governor.git
        path: ns-governor
        targetRevision: HEAD
        helm:
          valueFiles:
            # Move one level up to the parent directory
            - "../{{.path.path}}/{{.path.filenameNormalized}}"
          values: |
            namespace: "{{.path.basenameNormalized}}-{{ index (splitList "." .path.filenameNormalized) 0 }}-ns"
      destination:
        server: '{{.destinationServer}}'
        namespace: argocd
