apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ns-governor
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holds the different namespace and tenancy-specific resources
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
